### ISSUE TITLE
Shells do not work with Reserved Weapon Slot when mod is enabled

### ISSUE THREAD

**Issue by RubyTheQuester** [Hypick122/BetterShotgun#22]
### Describe the bug

Shells no longer count as ammo for the Reserved Weapon Slot Mod

### Reproducible Test

Enable Reserved Ammo Slot with the Reserved Weapon Slot Mod, and pick up a shell. Will no longer go into the slot if you have this mod eanbled

### Anything else?

The bug did not exist in the previous version as of time of writing this

**Comment by Hypick122** [comment]
The problem is due to the fact that the window for reserved slots opens with Alt held down and therefore ReloadKeybind with almost any value (except E and leftalt) is not readable.

Use ReloadKeybind = E for now

If you set leftalt, then when you open the menu the shotgun will immediately start reloading/inspecting

**Comment by Hypick122** [comment]
In version [1.4.3](https://github.com/Hypick122/BetterShotgun/commit/17f556aeebe41b15260742ddf32aec82cc2b97f5#diff-5ba2d37902b4e4dc3f9e1dd0f4d38265132c9771806f1b915626fe8578828622R60), a check for ReservedItemSlotCore was added, now ReloadKeybind is automatically set to the [E] key.

This should solve the problem. Perhaps in the future I will make keybind changing compatible with this mod

**Comment by RubyTheQuester** [comment]
This fix does not fix the issue that was posted. The shells have always worked with reloading with the mod installed. The bug was not being put into the reserve item slot for the Reserved Weapon Slot's ammo slot. perhaps it is the scrap thing

**Comment by Hypick122** [comment]
Oh, I didn't read the original message correctly. You also wrote that this error did not exist in the previous version. Are you talking about 1.4.0?

**Comment by RubyTheQuester** [comment]
i believe so, i am sorry for responding so late. 1.4.1 is what i believe

**Comment by Hypick122** [comment]
Well, I've figured out what the problem is and I'll fix it in a future patch.
